plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

repositories {
    mavenCentral()
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.terraformersmc.com/releases/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    api("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
    api "com.terraformersmc:modmenu:${project.modmenu_version}"
    implementation "com.github.oshi:oshi-core:${project.oshi_version}"
    include("com.github.oshi:oshi-core:${project.oshi_version}")
}

ext.mod_version = "${project.mod_base_version}+${project.minecraft_version}"
version = ext.mod_version
ext.fabric_api_version = project.fabric_api_version.tokenize('+')[0]

loom {
    clientOnlyMinecraftJar()
}

processResources {
    inputs.properties([
        "mod_version": project.mod_version,
        "supported_minecraft_versions": project.supported_minecraft_versions,
        "loader_version": project.loader_version,
        "fabric_api_version": project.fabric_api_version,
        "cloth_version": project.cloth_version,
    ])

    filesMatching("fabric.mod.json") {
        expand([
            mod_version: project.mod_version,
            supported_minecraft_versions: project.supported_minecraft_versions,
            loader_version: project.loader_version,
            fabric_api_version: project.fabric_api_version,
            cloth_version: project.cloth_version,
        ])
    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(java_version))
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release.set(java_version.toInteger())
}


